// <auto-generated />
using System;
using ImageRipper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageRipper.Migrations
{
    [DbContext(typeof(PhotoContext))]
    [Migration("20221215000941_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("ImageRipper.Collage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.HasKey("Id");

                    b.ToTable("collages", (string)null);
                });

            modelBuilder.Entity("ImageRipper.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("Filename")
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<long?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<long?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("ImageRipper.Recording", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("recordings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
